### ISSUE TITLE
Create documentation (writing)

### ISSUE THREAD

**Issue by bartwr** [BlocklabNL/VEL#14]
## User Story

As an user, I want read how I can onboard myself, so I can start using the Virtual Energy Hub!

## Why

The website consists of information about the project. This part is almost ready.

Then, the user needs good documentation on how to buy requirements like a Raspberry Pi, how to configure the RPi in the first place, how to debug and how to contribute to the code.

Roles needed:

- Development
- Content
- Design

Estimated hours:

- 12 hours
- Bounty budget: 840 EUR equivalent

This bounty consists of creating the structure and writing the documentation text.

You can ask these roles for asistance:

- Development: 4 hours for guidance
- Design: 8-n hours for guidance, sourcing images & creating illustrations

## What

- You'll write the documentation
- You'll receive feedback on the documentation by test users & will update docs accordingly
- You'll communicate with the development team if you have questions
- You'll communicate with the designer to make the documentation pretty
- The documentation will be available in the [GitHub wiki](https://github.com/BlocklabNL/VEL/wiki)

Don't be scared on being creative. Think of video's, animations, flow charts, screencasts, etc ^.^

## Bounty Details

- Expected hours: 12
- Before you start on this project, mention it in the comments
- Commit quick & often
- Only one pull request can be merged. In case multiple people worked on the task, the person that gets its PR merged has to take care of redistribution.

## How to test?

Test team will onboard itself. If they are confused or stuck in the process, the docs should be improved.

## Acceptance Criteria

The bounty solution can be applied as soon as the following is true:

- [x] Requirements for people that want to share data is documented
- [x] Every step of the process of "getting your smart meter data on bigchaindb" is documented
- [x] Every step of "register an account & see your personal dashboard" is documented
- [x] At least two people tested the documentation by setting up there own R.Pi connected to their smart meter

**Comment by Sus4nne** [comment]
I would like to do this one.

**Comment by bartwr** [comment]
Great to hear, @Sus4nne! We will notify you as soon as there're processes that can be documented :)

**Comment by bartwr** [comment]
- Requirements for people that want to share data is documented
- Every step of the process of "getting your smart meter data on bigchaindb" is documented
- Every step of "register an account & see your personal dashboard" is documented
- At least two people tested the documentation by setting up there own R.Pi connected to their smart meter

All checks are passed. :heavy_check_mark:

## Result

- https://github.com/OEHU/oehu-documentation/blob/master/getstarted.md
- https://oehu.org/get-started
