### ISSUE TITLE
Tester 2

### ISSUE THREAD

**Issue by bartwr** [BlocklabNL/VEL#16]
## User Story

As an end user, I want to have the onboarding process tested, so I can easily bring my data in the decentralized cloud.

## Why

...

## What

- Preferably you have a smart meter yourself
- You'll test the full proces of:
  - Connecting & configuring the Pi
  - Seeing your data coming in onto the platform
  - Testing logging in, logging out
- You'll have contact with the [documentation team](https://github.com/BlocklabNL/VEL/issues/14), for improving the docs

Bounty budget: 560 EUR equivalent.

## Bounty Details

- Expected hours: 8
- Before you start on this project, mention it in the comments
- Commit quick & often
- Only one pull request can be merged. In case multiple people worked on the task, the person that gets its PR merged has to take care of redistribution.

## How to test?

...

## Acceptance Criteria

The bounty solution can be applied as soon as the following is true:

- [ ] ...
- [ ] ...

**Comment by Sus4nne** [comment]
I would like to do this one.

**Comment by Sus4nne** [comment]
Done test with OEHU NOOBS package on a Rpi3. Works like a charm.
Done test with OEHU NOOBS package on a RPi2b. Does NOT work. See

**Comment by Sus4nne** [comment]
I added a couple of findings about the use of the website as issues on Github.
https://github.com/OEHU/oehu-website/issues/12#issue-379434504
https://github.com/OEHU/oehu-website/issues/11#issue-379429326
https://github.com/OEHU/oehu-website/issues/10#issue-379428738

**Comment by bartwr** [comment]
Susanne tested the full onboarding proces & gave valueable feedback. :heavy_check_mark: completed!
