### ISSUE TITLE
Communication: Manage social interaction

### ISSUE THREAD

**Issue by bartwr** [BlocklabNL/VEL#18]
## User Story

As Virtual Energy Hub, I want to be promoted, so I can be used & improved by many users.

## Why

People have to know about this project, so they can onboard their smart meter, they learn about distributed networks, do analysis & give feedback.

## What

The project needs to be promoted. We have set up a Twitter account, Telegram group, LinkedIn group and mailing list. Now there will be some communication on this channels.

This bounty is for promoting the project via social channels als well as managing the interaction that takes place on the socials.

We've estimated 0.25h / day * 14 days of work, that gives 3.5 hours in total.

Bounty budget: 245 EUR equivalent.

If you like to do this task, please mention this in the comments.

## Bounty Details

- Expected hours: 3.5
- Before you start on this project, mention it in the comments
- Commit quick & often
- Only one pull request can be merged. In case multiple people worked on the task, the person that gets its PR merged has to take care of redistribution.

## How to test?

- [ ] Check if the social channels are updated regularly
- [ ] Check if content is applicable to the project
- [ ] Check if there's a followers base +- October 5th

## Acceptance Criteria

The bounty solution can be applied as soon as the following is true:

- [ ] You did the tests below "How to test"
- [ ] At least 2 team members of Open Energy Hub are happy with the result

**Comment by Sus4nne** [comment]
I would like to do this.

**Comment by bartwr** [comment]
During the weeks before the launch & during the BlockLab 1yr celebration event Susanne manages the social media channels, gave updates & promoted OEHU. :heavy_check_mark: completed
