### ISSUE TITLE
Raspberry Pi: Init script

### ISSUE THREAD

**Issue by bartwr** [BlocklabNL/VEL#2]
A Raspberry Pi has to be configured so it can be attached to a smart meter using a P1->USB cable. This issue defines a subtask to realize this:

- [ ] Initialization script that installed necessary software and generates a priv/pub key pair

Roles needed:

- Server management
- Development

Estimated hours:

- Init script: 12
- Bounty budget: 840 EUR equivalent

Video description:

[![VEH Intro video](https://img.youtube.com/vi/agYsi52gfgg/0.jpg)](https://www.youtube.com/watch?v=agYsi52gfgg)

**Comment by MickdeGraaf** [comment]
Would be cool if this could be created to be easy for non tech savvy people.
Maybe out of scope for now but I was thinking about something like this:

We could do a slightly modified linux distro that has all scripts on it and runs them on boot.
When the device is not initialised it exposes a webpage where a user can set it up.
If the device has a wifi network device it creates it's own wifi network where you can connect to it and setup the wifi connection.

A helper application for mac/windows can scan the local network for the device if it is connected to a wired network that than opens the webpage to set it up.

A lot of options hehe.

All in all I would love to work on this, beginning with a script to download dependencies and setup the keyPair.

**Comment by bartwr** [comment]
Sound good.

**Comment by bartwr** [comment]
This will be the flow:

- [ ] On our site we offer an custom made OS
- [ ] User copy->pastes this on the microSD
- [ ] User puts in microSD in Pi
- [ ] Pi boots
  - Installs packages like the web server & read-and-write script
- [ ] Pi creates hotspot
- [ ] User goes to `raspberry-pi` hostname and sees onboarding process
- [ ] Part of onboarding = selecting SSD of WiFi network & filling in WiFi password
- [ ] Best would be to change the default password from 'raspberry' to something else

**Comment by MickdeGraaf** [comment]
http://sirlagz.net/2013/01/22/script-starting-hostapd-when-wifi-goes-down/ Some docs on how to start hostapd when wifi is down to setup wifi password

**Comment by MickdeGraaf** [comment]
Setting wifi from nodejs: https://github.com/matrix-io/pi-wifi

**Comment by MickdeGraaf** [comment]
https://github.com/sabhiram/raspberry-wifi-conf web-gui-setup already done

**Comment by MickdeGraaf** [comment]
https://github.com/MickdeGraaf/wifi-setup/ made a webgui that handles setting of wifi credentials.

**Comment by bartwr** [comment]
The "init script" is finished. We made it like this:

- We install NOOBS
- We configure the Pi fully, following [this guide](https://github.com/OEHU/oehu-documentation/blob/master/pi/configure-pi.md#notes-links-to-other-projects-random-thoughts-and-so-on)
- We make a [custom NOOBS package](https://github.com/OEHU/oehu-documentation/blob/master/pi/create-custom-noobs.md#this-guide-explains-how-to-create-your-custom-noobs-os), that people can download as a ZIP

For the user, the user experience is the following:

- The user needs hardware, that she can buy via one simple link. See [Get started](https://oehu.org/get-started)
- The user connects the Pi to 1) the smart meter & 2) the power cord
- The Pi automatically boots & installs itself. Duration: 15 minutes
- The user navigates to http://oehu.local - It shows the setup, https://github.com/oehu/oehu-setup-api
  - The user registers the device on bigchaindb
  - The user registers an account for easy access to stats
- The user is redirected to their dashboard: hooray - data!

![image](https://user-images.githubusercontent.com/899234/48304650-39b86c00-e51d-11e8-8eba-3dec1dd6226a.png)
