### ISSUE TITLE
Define data format for uploading in bigchaindb database

### ISSUE THREAD

**Issue by bartwr** [BlocklabNL/VEL#22]
We need to define a data format which we will use to upload smart meter data to bigchaindb.

This issue can be used to brainstorm about this. The issue can be closed if we defined and agreed on the data format to use.

**Comment by bartwr** [comment]
I think the current would be the amount of Ampère used at the moment of the data read. In the data format you shared it gives the realtime current of L1, L2 & L3.

```    "instantaneous": {
      "current": {
        "L1": {
          "reading": 1,
          "unit": "A"
        },
        "L2": {
          "reading": 2,
          "unit": "A"
        },
        "L3": {
          "reading": 3,
          "unit": "A"
        }
      },
```
The data that is received from the smart meter also gives realtime power statistics:

```
      "power": {
        "positive": {
          "L1": {
            "reading": 0.001,
            "unit": "kW"
          },
          "L2": {
            "reading": 0.002,
            "unit": "kW"
          },
          "L3": {
            "reading": 0.003,
            "unit": "kW"
          }
        },
        "negative": {
          "L1": {
            "reading": 0.004,
            "unit": "kW"
          },
          "L2": {
            "reading": 0.005,
            "unit": "kW"
          },
          "L3": {
            "reading": 0.006,
            "unit": "kW"
          }
        }
      }
    }```

Not sure if this can be interesting data to use for analysis.

Most important would be:

```  "electricity": {
    "received": {
      "tariff1": {
        "reading": 0.9,
        "unit": "kWh"
      },
      "tariff2": {
        "reading": 0,
        "unit": "kWh"
      },
      "actual": {
        "reading": 0.1,
        "unit": "kW"
      }
    },
    "delivered": {
      "tariff1": {
        "reading": 0,
        "unit": "kWh"
      },
      "tariff2": {
        "reading": 0,
        "unit": "kWh"
      },
      "actual": {
        "reading": 0,
        "unit": "kW"
      }
    }
  },```

That is the amount of kWh used in the last $timeInterval seconds.

**Comment by bartwr** [comment]
Max, Ilhan and I thought of what data format should be used.

Our conclusion was: We need to find out if there's a standard data format for smart meter data already. A protocol like thing. Search for familiar projects and see what they do. Look up open energy data projects. If there's no standard data format for smart meter data yet, we should define our own.

![image](https://user-images.githubusercontent.com/899234/45255256-476a3d80-b384-11e8-8fe5-fdda0ce370c2.png)

**Comment by bartwr** [comment]
![image](https://user-images.githubusercontent.com/899234/45255378-e6436980-b385-11e8-8fa7-3c77971dfa6d.png)

In bigchaindb there'll be one large object with device data.

The initial transaction can have:

- deviceId
- deviceType
- geolocation (with x meters precision)
- household type?
- number of occupants?
- age of accupants?

From the moment a device is registered in bigchaindb, we can append data transactions to it. We need something like:

- timestamp
- electricityReceived: {tarrif1: 0.1, tarrif2: 0.2}
- electricityDelivered: {tarrif1: 0.1, tarrif2: 0.2}
- gasReceived: 3

Can you @MickdeGraaf, as part of https://github.com/BlocklabNL/VEL/issues/4, find out what data format would be best, while having in mind that it must be easy & fast to query bigchaindb in the future?

**Comment by MickdeGraaf** [comment]
I believe bigchaindb works with mongodb for querying on the background.

I'm not very experienced with mongodb and don't know the ins and outs but whatever is efficient there should work.

Also are there any countries where there are even more than two tariffs? Or only one?
This might work: 

```
{
    timestamp: 00000000001;
    electricityReceived : {
        total: 0.7,
        tarrif1: 0.5,
        tariff2: 0.2
        (and so on)
    }
    electricityDelivered : {
        total: 0.7,
        tarrif1: 0.5,
        tariff2: 0.2
        (and so on)
    },
    gasReceived: 3
}
```
Keeping track of the total would make querying less intensive I think.

**Comment by MickdeGraaf** [comment]
https://github.com/MickdeGraaf/veh-bigchaindb-uploader/commit/d94a43f52d7bee2ab2e981b32e63587686c17f76 updated it to above data format for now.

**Comment by bartwr** [comment]
Data format defined. Issue can be closed now.
