### ISSUE TITLE
Raspberry Pi: Smart meter data reading

### ISSUE THREAD

**Issue by bartwr** [BlocklabNL/VEL#4]
A Raspberry Pi has to be configured so it can be attached to a smart meter using a P1->USB cable. This issue defines a subtask to realize this:

- [ ] Script that reads the smart meter data

Roles needed:

- Development

Estimated hours:

- Smart meter data reading: 20
- Bounty budget: 1400 EUR equivalent

**Comment by MickdeGraaf** [comment]
Would love to work on this.

**Comment by MickdeGraaf** [comment]
https://github.com/ruudverheijden/node-p1-reader/pull/15

My pull request to this repo was merged fixing the emulator.
That module should do anything we need but we need to think about the data format to use so I can convert it to so we can close this one.

**Comment by bartwr** [comment]
The reading of the smart meter data works well. Find the library at [veh-read-and-write](https://github.com/MickdeGraaf/veh-read-and-write). It gets automatically installed by the [init script](https://github.com/BlocklabNL/VEL/issues/2).

**Description of how reading works**

- Reading is done by the [p1-reader library](https://github.com/MickdeGraaf/veh-read-and-write/blob/master/src/index.js#L1)
- Reading is done at most once per 10 seconds. https://github.com/MickdeGraaf/veh-read-and-write/blob/master/src/index.js#L19
- Data is converted to this data standard: https://github.com/MickdeGraaf/veh-read-and-write/blob/master/src/index.js#L35

**Implemented - issue can be closed** :tada:
