### ISSUE TITLE
Raspberry Pi: Smart meter data uploading

### ISSUE THREAD

**Issue by bartwr** [BlocklabNL/VEL#5]
A Raspberry Pi has to be configured so it can be attached to a smart meter using a P1->USB cable. This issue defines a subtask to realize this:

- [ ] Script that uploads smart meter data to bigchaindb

Roles needed:

- Development

Estimated hours:

- 15 hours
- Bounty budget: 1050 EUR equivalent

**Comment by MickdeGraaf** [comment]
Would love to work on this.

**Comment by MickdeGraaf** [comment]
https://github.com/MickdeGraaf/veh-bigchaindb-uploader

Put the code that was already there in a module and added some stuff in. Does basic reading and stuff. Data format needs finalising before I can go further

**Comment by bartwr** [comment]
The smart meter data uploading works well. => Closed. You'll receive your bounty soon
