### ISSUE TITLE
Website design

### ISSUE THREAD

**Issue by bartwr** [BlocklabNL/VEL#8]
## User Story

As an user, I want to be able to view a website, so I can get info about the Open Energy Hub.

## Why

A website is nice to give a good overview of the project. It's also used for promotional purposes and onboarding new users. To make the website attractive to use, we need a good design.

## What

- Project information + Documentation
- Sign up for newsletter (MailChimp)
- Data explorer
  - List of 1000 latest data records
  - Map of data points of last month
- User registration + login
  - Personal dashboard
  - Logout

For proposed site text, see [Virtual Energy Lab - Project document](https://docs.google.com/document/d/1tZG8RnFNLKq3EFgprMTs7cIGW9bD3aMYjgqLSROZKys/edit#). Feel free to alter this so it fits the design.

## Bounty Details

- Estimated hours (website design only): 20
- Before you start on this project, mention it in the comments
- Commit quick & often
- Only one pull request can be merged. In case multiple people worked on the task, the person that gets its PR merged has to take care of redistribution.

Expect 3 revisions.

## How to test?

- [x] The website design should have all content listed under "What".
- [x] The website design should be tested by at least 10 people of our target group.

## Acceptance Criteria

The bounty solution can be applied as soon as the following is true:

- [ ] The tests under "How to test" are passed
- [ ] The design is offered in the format that is OK to use for the frontend developer

**Comment by bartwr** [comment]
Partly by https://studiospass.com/ ? Partly by @marijnbent

**Comment by ilhanu** [comment]
Is it possible to make this 20 hours ?

**Comment by bartwr** [comment]
Updated the amount of hours available for this to 20 hours. @ilhanu

**Comment by bartwr** [comment]
Website design is created by Jaron.

- First sketches: [OEHU_presentatie01_Spass.pdf](https://github.com/OEHU/oehu-identity/blob/master/identity/OEHU_presentatie01_Spass.pdf)
- Landing: [OEHU_Website_landingpage_01.jpg](https://github.com/OEHU/oehu-identity/blob/master/website/)
- Setup: https://github.com/OEHU/oehu-identity/tree/master/website
- Illustrations: https://github.com/OEHU/oehu-identity/tree/master/website/SVGS

____

I did the following checks:

〰️ **1) The website design should have all content listed under "What".**

- ✅ Project information + Documentation
- ✅ Sign up for newsletter (MailChimp)
- ✅ Data explorer
  - ❌ List of 1000 latest data records
  - ✅ Map of data points of last month
- ✅ User registration + login
  - 〰️ Personal dashboard
  - ❌ Logout

✅ **2) The website design should be tested by at least 10 people of our target group.**

____

Although not every check did pass, in the process the designer designed every part we needed for the product. The presentation, icons, example flyers & logo's, map, meters & setup function as a style guide that we can apply on every part of the OEHU product. Therefor this issue can be seen as 

=> **closed**
